Binary support
premAI-io/prem-app pull request #386
Opened 2023-10-18 16:37 UTC by Janaka-Steph

All the files are written at `$USER/Library/Application \Support/io.premai.prem-app`

2023-10-20 12:53 UTC, swarnimarun requested changes

2023-10-20 12:53 UTC, swarnimarun commented on src-tauri/src/main.rs
> +                let _ = controller_binaries::stop_all_services(event.window().state());
async function called without await, won't run.

2023-10-20 14:48 UTC, Janaka-Steph commented on src-tauri/src/main.rs
> +                let _ = controller_binaries::stop_all_services(event.window().state());
Ok but processes are killed when app is killed, we can check with `lsof -i -P -n | grep LISTEN`

2023-10-20 14:50 UTC, Janaka-Steph commented on src-tauri/src/main.rs
> +                let _ = controller_binaries::stop_all_services(event.window().state());
Maybe we don't even need to kill services manually

2023-10-20 14:51 UTC, Janaka-Steph commented on src-tauri/src/controller_binaries.rs
> +}
`state.running_services.lock()` returns a Future so need async

2023-10-21 15:39 UTC, swarnimarun commented on src-tauri/src/controller_binaries.rs
> +}
```suggestion
pub fn stop_all_services(state: tauri::State<'_, SharedState>) {
    tauri::async_runtime::block_on(async move {
        let services = state.running_services.lock().await;
        for service_id in services.keys() {
            _ = stop_service(service_id.clone(), state.clone()).await;
        }
    })
}
```

2023-10-21 15:40 UTC, swarnimarun commented on src-tauri/src/controller_binaries.rs
> +}
this should make it a sync function so that you can trivially use it in sync context. without having to await it.

2023-10-21 15:41 UTC, swarnimarun commented on src-tauri/src/main.rs
> +                let _ = controller_binaries::stop_all_services(event.window().state());
They are child processes, they will die, once the parent process is killed.

2023-10-21 15:41 UTC, swarnimarun commented on src-tauri/src/main.rs
> +                let _ = controller_binaries::stop_all_services(event.window().state());
But if in future we detach any service process from the parent process they would need cleanup.

2023-10-21 15:47 UTC, swarnimarun commented on src-tauri/src/controller_binaries.rs
> +}
also note I don't have a `?` in there as it's unneeded, we may want to log a failure to close, but otherwise it's bad to not run stop_service for other services if anyone of them fails.

Note: `?` is basically a throw statement, it will end execution of the function at that point, hence all the other services won't be stopped if one of the services before it fails to stop.

2023-10-24 13:25 UTC, tiero commented
The Rust code should prevent starting download multiple times if is already in progress.

```
src/download.rs:210 2023-10-24T15:24:12 [INFO] - downloaded 26%: (/Users/tiero/Library/Application Support/prem.tauri.dev/models/mistral-7b-openorca/mistral-7b-openorca.Q5_K_S.gguf):  1299409368 bytes / 4997728000 bytes
src/controller_binaries.rs:334 2023-10-24T15:24:18 [INFO] - service_id: mistral-7b-openorca
src/download.rs:210 2023-10-24T15:24:24 [INFO] - downloaded 27%: (/Users/tiero/Library/Application Support/prem.tauri.dev/models/mistral-7b-openorca/mistral-7b-openorca.Q5_K_S.gguf):  1349392528 bytes / 4997728000 bytes
src/download.rs:210 2023-10-24T15:24:33 [INFO] - downloaded 19%: (/Users/tiero/Library/Application Support/prem.tauri.dev/models/mistral-7b-openorca/mistral-7b-openorca.Q5_K_S.gguf):  949581107 bytes / 4997728000 bytes
src/download.rs:210 2023-10-24T15:24:38 [INFO] - downloaded 28%: (/Users/tiero/Library/Application Support/prem.tauri.dev/models/mistral-7b-openorca/mistral-7b-openorca.Q5_K_S.gguf):  1399368152 bytes / 4997728000 bytes
src/download.rs:210 2023-10-24T15:24:48 [INFO] - downloaded 29%: (/Users/tiero/Library/Application Support/prem.tauri.dev/models/mistral-7b-openorca/mistral-7b-openorca.Q5_K_S.gguf):  1449343714 bytes / 4997728000 bytes
src/download.rs:210 2023-10-24T15:24:57 [INFO] - downloaded 20%: (/Users/tiero/Library/Application Support/prem.tauri.dev/models/mistral-7b-openorca/mistral-7b-openorca.Q5_K_S.gguf):  999550731 bytes / 4997728000 bytes
src/download.rs:210 2023-10-24T15:25:00 [INFO] - downloaded 30%: (/Users/tiero/Library/Application Support/prem.tauri.dev/models/mistral-7b-openorca/mistral-7b-openorca.Q5_K_S.gguf):  1499326936 bytes / 4997728000 bytes
```

2023-10-24 13:35 UTC, tiero commented
1. We should have a guard in download_file 
2. The UI does not shows the right progress when two models are downloaded at the same time

2023-10-24 13:54 UTC, filopedraz commented
4. The settings icon is there. It's just covered by the flower when in dev mode.

2023-10-24 19:17 UTC, tiero commented
Message not supported should be

"This models is only available on Prem Server installation"

2023-10-25 12:22 UTC, tiero commented
I would add a checkbox or toggle on the top right that says "Show only available services" that hides all the not usable services. It's ok to start "un-checked" or "un-toggled"

2023-10-25 12:24 UTC, tiero commented
Also as improvement, I would prevent the user to use the playground of the service is the model is not loaded in memory, otherwise an uase that click on the Open and try to chat right away with Mistra will have "Load failed" error

2023-10-25 15:11 UTC, merged