Swarm Mode Enhancements
premAI-io/prem-app pull request #440
Opened 2023-10-27 12:28 UTC by nsosio

2023-10-27 14:21 UTC, Janaka-Steph commented on src-tauri/src/swarm.rs
> +    let python = env.get(&String::from("PREM_PYTHON")).unwrap().to_string();
unwrap is unsafe. Will crash if there is no env var, no?

2023-10-27 14:31 UTC, casperdcl requested changes
- missing `src-tauri/petals/run_swarm.sh` (which basically should contain the lines deleted from `src-tauri/petals/create_env.sh`)
- merge `swarm::install_swarm_requirements` and `swarm::run_swarm`
  + they should just run `run_swarm.sh`

2023-10-27 14:31 UTC, casperdcl commented on src-tauri/src/main.rs
> +            swarm::run_swarm,
would combine these two (it's ok to run `pip install` before each run, it'll be quick)

2023-10-27 14:31 UTC, casperdcl commented on src-tauri/src/swarm.rs
> +    let python = env.get(&String::from("PREM_PYTHON")).unwrap().to_string();
Too  many new functions with poor names. I think this `env` isn't from env vars, it's produced by a hardcoded function further down :D

2023-10-27 14:32 UTC, casperdcl commented on src-tauri/src/swarm.rs
> +    let python = env.get(&String::from("PREM_PYTHON")).unwrap().to_string();
Too many new functions with poor names. I think this `env` isn't from env vars, it's produced by a hardcoded function further down :D

2023-10-27 14:32 UTC, swarnimarun commented on src-tauri/src/swarm.rs
> +    let python = env.get(&String::from("PREM_PYTHON")).unwrap().to_string();
It will. We should consider, `unwrap_or` to provide a default value or return a Result/Option and early exit with error.

```suggestion
    let python = env.get(&String::from("PREM_PYTHON")).unwrap_or_else(|| &"/default/path".to_string()).clone();
```

2023-10-27 14:38 UTC, swarnimarun commented on src-tauri/src/swarm.rs
> +        .envs(env.clone())
```suggestion
        .env_clear()
        .envs(&env)
```

Call env clear on command to ensure nothing gets overwritten. And clone isn't required.

2023-10-27 14:56 UTC, swarnimarun commented on src-tauri/src/swarm.rs
> +        .expect("🙈 Failed to install requirements");
```suggestion
    let exit_status = Command::new(&pip)
        .args([
            "install",
            "-r",
            &requirements
        ])
        .spawn()
        .expect("🙈 Couldn't start `pip install -r $PETALS_PATH/requirements.txt`")
        .wait()
        .expect("🙈 Didn't run `pip install -r $PETALS_PATH/requirements.txt");
    if !exit_status.success() {
        eprintln!("🙈 Failed to `pip install -r $PETALS_PATH/requirements.txt");
    }
```

Output returns an error only if the command failed to execute, the command itself could still fail and you won't report or break on it.


Also I recommend using Result over directly using `expect` it's essentially the same as unwrap so it will crash the app if the command fails.

2023-10-27 14:57 UTC, nsosio commented on src-tauri/src/main.rs
> +            swarm::run_swarm,
I had to split them because the installation can take some time and I wanted to keep the user experience as it was before (meaning the setup of the swarm is concluded when petal server is started).
- expected behaviour ([commit 351f982](https://github.com/nsosio/prem-app/commit/351f9827e23d09c83412ef96f4126ef8945e2b49)) 
- unexpected behaviour ([commit 778d215](https://github.com/nsosio/prem-app/commit/778d215ee51f3f93214ae8d31ad9d3eeb9eb9bd5))

https://github.com/premAI-io/prem-app/assets/5698130/14cf650a-8a75-4638-bb1b-9c9fe127835d

https://github.com/premAI-io/prem-app/assets/5698130/7d56683e-84dc-4dc0-abb0-cd0ed56833fe

2023-10-27 15:02 UTC, nsosio commented on src-tauri/src/swarm.rs
> +    let python = env.get(&String::from("PREM_PYTHON")).unwrap().to_string();
@casperdcl in this case which default value would we use?

2023-10-27 16:00 UTC, nsosio commented on src-tauri/src/swarm.rs
> +        .envs(env.clone())
@swarnimarun Command is a tauri [Command](https://docs.rs/tauri/latest/tauri/api/process/struct.Command.html) and expect  `HashMap<String, String>`

2023-10-27 16:01 UTC, nsosio commented on src-tauri/src/swarm.rs
> +        .expect("🙈 Failed to install requirements");
@swarnimarun Command is a tauri [Command](https://docs.rs/tauri/latest/tauri/api/process/struct.Command.html) and does not have `wait()`

2023-10-27 18:12 UTC, casperdcl commented on src-tauri/src/swarm.rs
> +    let python = env.get(&String::from("PREM_PYTHON")).unwrap().to_string();
just `python` from the user's `PATH` :)

```suggestion
    let python = env.get(&String::from("PREM_PYTHON")).unwrap_or_else(|| &"python".to_string()).clone();```

2023-10-27 18:38 UTC, casperdcl commented on src-tauri/src/main.rs
> +            swarm::run_swarm,
maybe I'm tired but I can't figure out what's the difference between the two screen recordings

2023-10-27 18:49 UTC, nsosio commented on src-tauri/src/main.rs
> +            swarm::run_swarm,
In the **unexpected behaviour**, the modal (i.e. swarm is started) opens when the requirements haven't been installed yet and no process has been started (see in the terminal swarm processes started later). While in the **expected behaviour**,  the modal opens when the swarm starts (see in the terminal swarm processes start at almost the same time).

2023-10-27 19:09 UTC, casperdcl commented on src-tauri/src/main.rs
> +            swarm::run_swarm,
ah I see, thanks. Seems a lot of extra code complexity just to have the modal pop up post- rather than pre- requirements install. Not sure it's a good trade-off but up to you I guess.

2023-10-27 19:26 UTC, nsosio commented on src-tauri/src/main.rs
> +            swarm::run_swarm,
It makes sense, let's keep it simpler. I'll roll it back :)

2023-10-30 11:20 UTC, nsosio commented on src-tauri/src/main.rs
> +            swarm::run_swarm,
Done

2023-10-30 11:21 UTC, nsosio commented on src-tauri/src/swarm.rs
> +        .envs(env.clone())
done

2023-10-30 11:21 UTC, nsosio commented on src-tauri/src/swarm.rs
> +        .expect("🙈 Failed to install requirements");
Removed install requirements

2023-10-30 11:22 UTC, nsosio commented on src-tauri/src/swarm.rs
> +    let python = env.get(&String::from("PREM_PYTHON")).unwrap().to_string();
Merged

2023-10-30 12:42 UTC, casperdcl commented on src-tauri/petals/run_swarm.sh
> +prem_python="${PREM_PYTHON:-.}"
```suggestion
prem_python="${PREM_PYTHON:-python}"
```

2023-10-30 12:47 UTC, casperdcl commented on src-tauri/src/swarm.rs
> +    }
do we haz linters to fix these accidents?

2023-10-30 12:52 UTC, nsosio commented on src-tauri/src/swarm.rs
> +    }
AFAIK we don't have anything for rust code base only for js

2023-10-30 13:07 UTC, tiero commented
If I shutdown the computer after running the swarm and re-open the app on restart it will show the button Stop, even if no processes are not actually running. Are we able to check at runtime if the python process for the swar mode is actually running?

2023-10-30 13:10 UTC, tiero commented
If the environment is already setup but stopped, we should allow user to "Delete" the environment (cc/ @nsosio uninstall/clean script). This is also useful to visually test all the possible states from UI, without to manually delete `.config/prem`

2023-10-30 13:18 UTC, tiero commented
I would also show the Server ID and the model along with number of block when we are running

<img width="877" alt="image" src="https://github.com/premAI-io/prem-app/assets/3596602/63f76a40-d7ec-4f45-b06b-19b56e8fee7c">

2023-10-30 13:19 UTC, nsosio commented
> If I shutdown the computer after running the swarm and re-open the app on restart it will show the button Stop, even if no processes are not actually running. Are we able to check at runtime if the python process for the swar mode is actually running?

@tiero I'll add a check on the python processes

> If the environment is already setup but stopped, we should allow user to "Delete" the environment (cc/ @nsosio uninstall/clean script). This is also useful to visually test all the possible states from UI, without to manually delete .config/prem
@tiero I'll add it

2023-10-30 13:23 UTC, tiero commented
To give more context, doing everything clean, the logs have `:` but no Process IDs as before is logged. Not sure if it was intentional

```sh
🐍 Creating the environment...
🚀 Starting the Swarm...
🛑 Stopping the Swarm...
🛑 Stopping Processes:
🛑 Stopping Process:
🛑 Stopped all the Swarm Processes.
```

2023-10-30 13:33 UTC, casperdcl requested changes

2023-10-30 13:33 UTC, casperdcl commented on src-tauri/src/swarm.rs
>          .expect("🙈 Failed to create env");
```suggestion
        .expect("🙈 Failed to create env");
    env
```

2023-10-30 13:33 UTC, casperdcl commented on src-tauri/src/swarm.rs
> +    env.insert("PREM_PYTHON".to_string(), python);
```suggestion
    let env = create_environment(handle);
```

2023-10-30 13:33 UTC, casperdcl commented on src-tauri/src/swarm.rs
> +    let prem_app_env = format!("{app_data_dir}/miniconda/envs/prem_app");
could pass in `handle` then:

```suggestion
    let env = create_environment(handle);
    let python_path = PathBuf::from(env.get(&String::from("PREM_PYTHON")).unwrap().to_string());
    let prem_app_env = python_path.parent().unwrap().parent().unwrap().to_str().unwrap();
```

2023-10-30 13:36 UTC, nsosio commented
> To give more context, doing everything clean, the logs have `:` but no Process IDs as before is logged. Not sure if it was intentional
> 
> ```shell
> 🐍 Creating the environment...
> 🚀 Starting the Swarm...
> 🛑 Stopping the Swarm...
> 🛑 Stopping Processes:
> 🛑 Stopping Process:
> 🛑 Stopped all the Swarm Processes.
> ```

@tiero this is weird it means there is no process running even if the swarm has been started. I need to check it

2023-10-30 13:51 UTC, casperdcl commented on src-tauri/src/swarm.rs
>              });
btw I think `SIGTERM` (and/or `SIGINT`) are safer to try first before `SIGKILL`

2023-10-30 14:24 UTC, nsosio commented on src-tauri/src/swarm.rs
> +    let prem_app_env = format!("{app_data_dir}/miniconda/envs/prem_app");
do we want to launch the `create_env.sh` script every time we want to get the processes? It seems too much to me  🤔 (now the `get_swarm_processes` function is run every 500ms)

2023-10-30 14:54 UTC, casperdcl commented on src-tauri/src/swarm.rs
> +    let prem_app_env = format!("{app_data_dir}/miniconda/envs/prem_app");
why every 500ms? Can qe do 10x less?

2023-11-01 17:30 UTC, nsosio commented
- [x] merged  `swarm::install_swarm_requirements` and `swarm::run_swarm`
- [x] added deletion of swarm environment

Regarding:
-  [[1](https://github.com/premAI-io/prem-app/pull/440#issuecomment-1785157692)] I've created a new [issue](https://github.com/premAI-io/prem-app/issues/465)
-  [[2](https://github.com/premAI-io/prem-app/pull/440#discussion_r1376258099)] I've created a new [issue](https://github.com/premAI-io/prem-app/issues/464)

@tiero, @casperdcl and @swarnimarun can you check if we can merge this PR? The missing issues will be tackled in separate PRs

2023-11-01 18:24 UTC, casperdcl commented on src-tauri/petals/run_swarm.sh
> +prem_python="${PREM_PYTHON:-.}"
accidentally removed?

2023-11-01 18:28 UTC, nsosio commented on src-tauri/petals/run_swarm.sh
> +prem_python="${PREM_PYTHON:-.}"
yep my fault, rolled back :)

2023-11-01 18:41 UTC, tiero commented on src/modules/settings/components/SwarmMode.tsx
> +                  {<div>Delete Swarm Environment</div>}
```suggestion
                  {<div>Reset to default</div>}
```

2023-11-01 18:42 UTC, tiero commented
lets not mention Swarm in user-facing messages

 `Please do not close the app we are configuring the Swarm Environment` >  `Please do not close the app as we are configuring your environment for the Prem Network`

2023-11-01 18:43 UTC, tiero commented
other than that LGTM

tACK https://github.com/premAI-io/prem-app/pull/440/commits/6836a33673274a59bc5d8098424bf286f026a0c8

2023-11-02 08:24 UTC, casperdcl approved these changes
Thanks! Finally got there :)

2023-11-02 09:54 UTC, nsosio commented
Added bugfix to #465. Now on restart swarm state is correctly set.

2023-11-02 11:03 UTC, merged