[desktop] Registry support
premAI-io/prem-app pull request #459
Opened 2023-11-01 15:20 UTC by Janaka-Steph

2023-11-02 12:09 UTC, swarnimarun commented on src-tauri/src/main.rs
> +                if !store_path.exists() {
Any reason this couldn't be part of the add_registry function?

2023-11-02 12:14 UTC, Janaka-Steph commented on src-tauri/src/main.rs
> +                if !store_path.exists() {
Yes indeed, I will use add_registry here

2023-11-02 18:07 UTC, tiero commented
If I add a registry, then navigating to main page does not reflects the update unless I reload (ie/ close and reopen the app) is this a wanted behavior?

2023-11-02 18:09 UTC, tiero commented
The app crashed when I treid to download a service btw

```sh
-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               Prem [52977]
Path:                  /Users/USER/*/Prem
Identifier:            Prem
Version:               ???
Code Type:             ARM-64 (Native)
Parent Process:        cargo-tauri [52814]
Responsible:           stable [4861]
User ID:               501

Date/Time:             2023-11-02 19:08:19.3123 +0100
OS Version:            macOS 13.6 (22G120)
Report Version:        12
Anonymous UUID:        42645F01-64DE-A8ED-9848-E54656D5FC7A

Sleep/Wake UUID:       81047958-E7AA-434F-8677-FB5229454A48

Time Awake Since Boot: 17000 seconds
Time Since Wake:       5234 seconds

System Integrity Protection: enabled

Crashed Thread:        10  tokio-runtime-worker

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000

Termination Reason:    Namespace SIGNAL, Code 6 Abort trap: 6
Terminating Process:   Prem [52977]

Application Specific Information:
abort() called


Thread 0:: main Dispatch queue: com.apple.main-thread
0   libsystem_kernel.dylib        	       0x195cf3f34 mach_msg2_trap + 8
1   libsystem_kernel.dylib        	       0x195d06260 mach_msg2_internal + 80
2   libsystem_kernel.dylib        	       0x195cfcb98 mach_msg_overwrite + 604
3   libsystem_kernel.dylib        	       0x195cf42b0 mach_msg + 24
4   CoreFoundation                	       0x195e12774 __CFRunLoopServiceMachPort + 160
5   CoreFoundation                	       0x195e11054 __CFRunLoopRun + 1208
6   CoreFoundation                	       0x195e10448 CFRunLoopRunSpecific + 612
7   HIToolbox                     	       0x19f662df0 RunCurrentEventLoopInMode + 292
8   HIToolbox                     	       0x19f662c2c ReceiveNextEventCommon + 648
9   HIToolbox                     	       0x19f662984 _BlockUntilNextEventMatchingListInModeWithFilter + 76
10  AppKit                        	       0x19903797c _DPSNextEvent + 636
11  AppKit                        	       0x199036b18 -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 716
12  AppKit                        	       0x19902af7c -[NSApplication run] + 464
13  Prem                          	       0x10567c78c _$LT$$LP$$RP$$u20$as$u20$objc..message..MessageArguments$GT$::invoke::h6a9427288d50c8eb + 64
14  Prem                          	       0x105680b90 objc::message::platform::send_unverified::_$u7b$$u7b$closure$u7d$$u7d$::h23827bc5dbbcda11 + 52
15  Prem                          	       0x10567fa9c objc_exception::try::_$u7b$$u7b$closure$u7d$$u7d$::hfbc9e25c9cb49f0e + 44
16  Prem                          	       0x10567e1f8 objc_exception::try_no_ret::try_objc_execute_closure::h8060cf94af4086f9 + 76
17  Prem                          	       0x10568b29c RustObjCExceptionTryCatch + 36
18  Prem                          	       0x10567d800 objc_exception::try_no_ret::h7b2766aebf05be39 + 168
19  Prem                          	       0x10567e53c objc_exception::try::h006c6b0e5cb04a33 + 72
20  Prem                          	       0x105683e3c objc::exception::try::h934daa43fce53850 + 12
21  Prem                          	       0x10567ff38 objc::message::platform::send_unverified::h9ed31badc9da5cb0 + 136
22  Prem                          	       0x10502b6e4 objc::message::send_message::h6d6bba4eca7b94ec + 20 (mod.rs:178) [inlined]
23  Prem                          	       0x10502b6e4 tao::platform_impl::platform::event_loop::EventLoop$LT$T$GT$::run_return::hb3cd62bdaa43dce2 + 1120 (event_loop.rs:193)
24  Prem                          	       0x10502c708 tao::platform_impl::platform::event_loop::EventLoop$LT$T$GT$::run::hd2d0e6fb964d6c9e + 20 (event_loop.rs:160)
25  Prem                          	       0x104cb8ba4 tao::event_loop::EventLoop$LT$T$GT$::run::hc5436bc3c27b68a4 + 60 (event_loop.rs:179)
26  Prem                          	       0x105042d90 _$LT$tauri_runtime_wry..Wry$LT$T$GT$$u20$as$u20$tauri_runtime..Runtime$LT$T$GT$$GT$::run::h966c38c55658a370 + 492 (lib.rs:2256)
27  Prem                          	       0x104d30b34 tauri::app::App$LT$R$GT$::run::h65f6f110b7fd5034 + 280 (app.rs:875)
28  Prem                          	       0x104ba65bc prem_app::main::h36dc4feba6cf6022 + 13796 (main.rs:326)
29  Prem                          	       0x104df0f74 core::ops::function::FnOnce::call_once::h75b6e16fc958e634 + 20 (function.rs:250)
30  Prem                          	       0x104c43eb8 std::sys_common::backtrace::__rust_begin_short_backtrace::hb81574aa4dd80193 + 24 (backtrace.rs:135)
31  Prem                          	       0x104bdd1cc std::rt::lang_start::_$u7b$$u7b$closure$u7d$$u7d$::h66e540ff34fa8389 + 28 (rt.rs:166)
32  Prem                          	       0x105e1cff8 std::rt::lang_start_internal::hdd06e3566639fc5b + 648
33  Prem                          	       0x104bdd198 std::rt::lang_start::hae9d86873024fccb + 84 (rt.rs:165)
34  Prem                          	       0x104ba7358 main + 36
35  dyld                          	       0x1959dbf28 start + 2236

Thread 1:: sentry-transport
0   libsystem_kernel.dylib        	       0x195cf3eb0 semaphore_wait_trap + 8
1   libdispatch.dylib             	       0x195b8499c _dispatch_sema4_wait + 28
2   libdispatch.dylib             	       0x195b85050 _dispatch_semaphore_wait_slow + 132
3   Prem                          	       0x105e1d79c std::thread::park::hdee2c6520783473c + 56
4   Prem                          	       0x1051544a8 std::sync::mpmc::context::Context::wait_until::h2a892b2ea18151ce + 524
5   Prem                          	       0x10515d53c std::sync::mpmc::array::Channel$LT$T$GT$::recv::_$u7b$$u7b$closure$u7d$$u7d$::ha4826a7f1de44fe5 + 208
6   Prem                          	       0x10515552c std::sync::mpmc::context::Context::with::_$u7b$$u7b$closure$u7d$$u7d$::h39b405a6105417b8 + 196
7   Prem                          	       0x1051569a4 std::sync::mpmc::context::Context::with::_$u7b$$u7b$closure$u7d$$u7d$::hdab5280c8a612244 + 204
8   Prem                          	       0x1051671a4 std::thread::local::LocalKey$LT$T$GT$::try_with::h2b75dbf694226240 + 300
9   Prem                          	       0x105154cc4 std::sync::mpmc::context::Context::with::hdd745c5418276555 + 60
10  Prem                          	       0x10515d238 std::sync::mpmc::array::Channel$LT$T$GT$::recv::hcca5742f7efc6dd7 + 428
11  Prem                          	       0x105153f30 std::sync::mpmc::Receiver$LT$T$GT$::recv::h3beafb5026f10541 + 128
12  Prem                          	       0x105174154 _$LT$std..sync..mpsc..IntoIter$LT$T$GT$$u20$as$u20$core..iter..traits..iterator..Iterator$GT$::next::hfe730635d0cd13c8 + 40
13  Prem                          	       0x1051640c0 sentry::transports::tokio_thread::TransportThread::new::_$u7b$$u7b$closure$u7d$$u7d$::_$u7b$$u7b$closure$u7d$$u7d$::he3ed221107b66c7c + 364
14  Prem                          	       0x105139890 _$LT$core..pin..Pin$LT$P$GT$$u20$as$u20$core..future..future..Future$GT$::poll::h6b5ead7d461dfc20 + 60
15  Prem                          	       0x10514e3e0 tokio::runtime::scheduler::current_thread::CoreGuard::block_on::_$u7b$$u7b$closure$u7d$$u7d$::_$u7b$$u7b$closure$u7d$$u7d$::_$u7b$$u7b$closure$u7d$$u7d$::hd99f8f9cb3a47472 + 56
16  Prem                          	       0x10514e340 tokio::runtime::scheduler::current_thread::CoreGuard::block_on::_$u7b$$u7b$closure$u7d$$u7d$::_$u7b$$u7b$closure$u7d$$u7d$::hd3ba12cb860b6283 + 272
17  Prem                          	       0x10514d31c tokio::runtime::scheduler::current_thread::Context::enter::h7fdbe0edd4762d05 + 336
18  Prem                          	       0x10514dc44 tokio::runtime::scheduler::current_thread::CoreGuard::block_on::_$u7b$$u7b$closure$u7d$$u7d$::h1ca50ff4f16b0b1e + 428
19  Prem                          	       0x10514da10 tokio::runtime::scheduler::current_thread::CoreGuard::enter::_$u7b$$u7b$closure$u7d$$ [...]

2023-11-02 22:57 UTC, tiero commented
Add a button "Reset" to use the default registry URL in case user removes all of them

2023-11-02 23:06 UTC, tiero commented on src/modules/settings/components/Registries.tsx
>          </div>
We don't use the PluaArrow for anything, lets remove it? or replace the "Add Registry" button with this PlusArrow

2023-11-03 12:14 UTC, swarnimarun commented on src-tauri/src/utils.rs
> +    let mut handlers = vec![];
```suggestion
    let mut handlers = vec![];
    {
         let mut services_guard = state.services.lock().await;
         services_guard.clear();
     }
```

2023-11-07 09:46 UTC, swarnimarun commented on src-tauri/src/controller_binaries.rs
> +                serde_json::to_value(&new_registry).unwrap(),
```suggestion
        let new_registry = [&registry];
        store
            .insert(
                "registries".to_string(),
                serde_json::to_value(&new_registry).unwrap(),
```
no need to create a vector, both serialize to same Value.

2023-11-07 09:57 UTC, swarnimarun commented on src-tauri/src/utils.rs
> +    }
```suggestion
        if !service.get_id_ref().map(|id| services_guard.contains_key(id)).unwrap_or_default() {
            services_guard.insert(service.get_id()?, service);
        }
    }
```
No need to search if no id found.
Also, any reasons to use different ways of getting id in both cases?

2023-11-07 10:00 UTC, swarnimarun commented on src/controller/dockerController.ts
> +  }
Hmm, I think we should reopen this issue, https://github.com/premAI-io/prem-daemon/issues/85

2023-11-07 10:02 UTC, swarnimarun approved these changes
lgtm, just a couple nits for some performance.

2023-11-07 11:09 UTC, tiero commented
cargo check fails @swarnimarun

2023-11-07 17:01 UTC, tiero commented
@swarnimarun Please can you properly update the code using your siggestions?

It does not compile otherwise with a `error[E0308]: mismatched types`

2023-11-07 17:19 UTC, Janaka-Steph commented on src/controller/dockerController.ts
> +  }
That method is for docker env. Let's create a separate issue.

2023-11-08 11:10 UTC, swarnimarun requested changes
tested the new suggestions locally, also note, currently the project won't build on windows, should I fix it ??

2023-11-08 11:10 UTC, swarnimarun commented on src-tauri/src/controller_binaries.rs
> +        let new_registry = [&registry];
```suggestion
        let new_registry = [registry];
```

2023-11-08 11:10 UTC, swarnimarun commented on src-tauri/src/utils.rs
> +    registries: &Vec<Registry>,
```suggestion
    registries: &[Registry],
```

2023-11-08 12:05 UTC, tiero commented
> currently the project won't build on windows, should I fix it ??

Project works only for Mac M1, and we dont have binaries for Linux/Windows even

2023-11-08 12:20 UTC, swarnimarun approved these changes

2023-11-08 18:44 UTC, swarnimarun commented
@tiero I think we can merge now, what do you think?

2023-11-09 09:35 UTC, merged